# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# API routes with locale prefix
api:
    resource:
        path: ../src/Presentation/Controller/Api/
        namespace: App\Presentation\Controller\Api
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: 'en|fr|de|es|pt|nl'
    defaults:
        _locale: 'en'
